# Generated by Django 4.1.7 on 2023-03-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='images/', upload_to='pokemon_images'),
        ),
    ]
